### ISSUE TITLE
Coulnd't use with NeoVim

### ISSUE THREAD

**Issue by SerhatTeker** [sagi-z/oonav#3]
Hi @sagi-z,
This seems a great plugin. However I can't use it with *NeoVim*.

![Screenshot from 2021-04-26 23-39-33](https://user-images.githubusercontent.com/45147900/116147787-cdc81f00-a6e8-11eb-823b-823638c129a6.png)

I'm using **ludovicchabant/vim-gutentags** for tags and  my nvim version is **0.4.4** with details below.
What should we do to fix the issue?

```bash
NVIM v0.4.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-Fc1Pxf/neovim-0.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-Fc1Pxf/neovim-0.4.4/build/config -I/build/neovim-Fc1Pxf/neovim-0.4.4/src -I/usr/include -I/usr/include/lua5.1 -I/build/neovim-Fc1Pxf/neovim-0.4.4/build/src/nvim/auto -I/build/neovim-Fc1Pxf/neovim-0.4.4/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

p.s:
my  **perl** on the `$PATH`.

**Comment by sagi-z** [comment]
Hi, sorry but there is no nvim support for now. I will probably have time to look into this over the weekend.

**Comment by SerhatTeker** [comment]
No problem at all. Please tell me when you need something.

**Comment by SerhatTeker** [comment]
Thanks. Seems giving no error now. But the plugin now doesn't work: Doesn't have any mapping etc. even though `let g:oonav#create_mappings = 1`. Strange. As soon as have time I'll debug it. Closing till then.
